#ifndef _ONION_ADS1X15_DRIVER_MAIN_H_
#define _ONION_ADS1X15_DRIVER_MAIN_H_

#include <stdlib.h>

#include <onion-ads1x15-driver.h>

#define ADS1X15_MAIN_VERBOSITY_QUIET			(ADS1X15_SEVERITY_FATAL)
#define ADS1X15_MAIN_VERBOSITY_NORMAL			(ADS1X15_SEVERITY_INFO)
#define ADS1X15_MAIN_VERBOSITY_VERBOSE			(ADS1X15_SEVERITY_DEBUG)
#define ADS1X15_MAIN_VERBOSITY_EXTRA_VERBOSE	(ADS1X15_SEVERITY_DEBUG_EXTRA)

#define ADS1X15_MAIN_DEFAULT_VERBOSITY 			(ADS1X15_MAIN_VERBOSITY_NORMAL)
#define ADS1X15_MAIN_DEFAULT_DEBUG	 			(0)



struct adsSetup {
	int 	channel;
	int 	gain;

	// general options
	int 	verbose;
	int 	debug;
};


#endif // _ONION_ADS1X15_DRIVER_MAIN_H_